version: "3.8"

services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devpass
    networks:
      - postgres-compose-network
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
  pgadmin:
     image: dpage/pgadmin4
     container_name: pgadmin
     environment:
       PGADMIN_DEFAULT_EMAIL: "marcosgabrielmiller@gmail.com"
       PGADMIN_DEFAULT_PASSWORD: "devpass"
     ports:
       - "16543:80"
     depends_on:
       - postgres
     networks:
       - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
