version: '3.9'
services:
  apache:
    image: php:8.1.6-apache
    container_name: apache-php
    #restart: always
    ports:
      - '3000:80'
    volumes:
      - ./website:/var/www/html
  mysql:
    image: mysql:8.0
    container_name: mysql
    #restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: devpass
    volumes:
      - ./mysql:/var/lib/mysql
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    #restart: always
    ports:
      - '30001:80'
    environment:
      PMA_HOST: mysql
